##### TPM plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'tmux-plugins/tmux-resurrect'   # restore sessions
# set -g @plugin 'tmux-plugins/tmux-continuum'   # auto-save sessions - only enable if you need it
set -g @plugin 'tmux-plugins/tmux-yank'        # copy to system clipboard

# Options to make tmux more pleasant
set -g mouse on # Enable if mouse mode is needed!
set -g default-terminal "tmux-256color"
set -g history-limit 50000

# Indexing from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Disable automatic window renaming
set -g allow-rename off
setw -g automatic-rename off

# Continuum config
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '10' # save every 10 seconds

run '~/.tmux/plugins/tpm/tpm'